<script setup lang="ts">
import { useData } from "vitepress";

const { site } = useData();
const currentYear = new Date().getFullYear();
</script>

<template>
  <footer>
    {{ currentYear }} {{ site.title }} | Generated by
    <a href="https://github.com/ridzimeko/mekonote">Mekonote</a>
  </footer>
</template>

<style scoped>
footer {
  text-align: center;
  margin-top: 3rem;
  padding: 1rem 0;
  font-size: 15px;
}
</style>
